### ISSUE TITLE
Official Repo?

### ISSUE THREAD

**Issue by justingeeslin** [scoy/KoduGameLab#5]
Hey scoy!

I’m a long time user of Kodu (since about 2013), and I’ve very happy to see it open sourced! 

Question: **Is this the official repo in which interested people should submit issues and PRs?**

There’s another Kodu Game Lab repo out there under the MS Org. It’s tough to tell between this repo and that one which is the most active.
https://github.com/microsoft/KoduGameLab

Thanks! And Thanks for your work on Kodu!

**Comment by scoy** [comment]
The MS repo is the original one which was used to get Kodu into the open source world.  This repo is the only that I'll be working out of going forward.  It will be the only one updated, etc.  I'm still figuring out GitHub so any issues you have may get my notice quicker by emailing me at KoduSupport@InfiniteInstant.com
